---
- name: "{{ service_name }} | Set manifest path"
  ansible.builtin.set_fact:
    k8s_manifest_path: "{{ k8s_directory }}/{{ manifest }}"

- name: "{{ service_name }} | {{ operation | title }} {{ manifest }}"
  kubernetes.core.k8s:
    state: "{{ k8s_manifest_state }}"
    definition: "{{ lookup('file', '{{ k8s_manifest_path }}') | from_yaml_all }}"
    validate:
      fail_on_error: true # fail on validation errors
      strict: true        # check for unexpected properties
